version: "3.9"
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse
    ports:
      - "88:88"
    volumes:
      - .nginxconf:/etc/nginx
    networks:
      - front  

networks:
  front:
    name: front
    driver: overlay

